### ISSUE TITLE
Create a "New Plugin" Issue template

### ISSUE THREAD

**Issue by pascalwilbrink** [openscd/open-scd#1521]
In order to enforce the community to come up with great new ideas for plug-ins, we can create a new GitHub issue template for new plugins.

Example:

```yml
name: New plug-in
description: Have a new plug-in Idea? File it here
title: "[new Plug-in idea]: "
labels: ["plugin", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new plug-in report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: idea
    attributes:
      label: What is your idea?
      description: Please be as specific as possible
      placeholder: Please tell us your idea!
      value: "I would like a plug-in that ..."
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: What type of plug-in should it be?
      multiple: true
      options:
        - Menu
        - Editor
    validations:
      required: true
  - type: textarea
    id: mockups
    attributes:
      label: Relevant mockups
      description: If you have any mockups, please attach them here
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/openscd/.github/blob/main/profile/code_of_conduct.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
```
*Acceptance criteria*:
- [ ] Issue template exists in `.github` folder.
- [ ] New label `new plug-in` exists (with a nice color :) )
