### ISSUE TITLE
Filtering in Cleanup Editor for Control Blocks broken

### ISSUE THREAD

**Issue by danyill** [openscd/open-scd#873]
**Describe the bug**

**To Reproduce**

1. Load an scd file with controls blocks which refer to missing or invalid datasets
2. Attempt to filter as shown in (1) below.
3. Observe near (2) below that no filtering occurs
4. Observe that the Unreferenced Datasets widget works at (3) (with correct filtering) and regain a little strength.
5. Nonetheless burst into tears :cry:, this used to work...

Perhaps something to do with the reactive change? But updates after button clicks appear to work fine.
I shall investigate in the fullness of time.

**Expected behavior**

The filter filters based on the text.

**Screenshots**

![image](https://user-images.githubusercontent.com/674783/178710129-23fb8cf4-0507-4be8-9bb0-ca886daa3ed8.png)

**Comment by danyill** [comment]
Each `mwc-check-list-item` that should not be included after a filter is typed appears to correctly have the class `hidden` applied and the remaining ones do not have this class, so the filter function appears to be functioning correctly.

This appears to be a display refresh issue as the `hidden` CSS is not forcing a refresh of the element and so may be related to the general "reactive update" issue.

**Comment by danyill** [comment]
I have tried a variety of things.

* `this.requestUpdate()`
* `this.requestUpdate()` in the `onFilterInput` of `filtered-list.ts`.
* `this.render()` in `filtered-list.ts`
* `super.requestUpdate()`

Various combinations of the above and a dose of google.
The CSS looks fine, yet the component doesn't update on a class change.
Other filtered lists appear to work fine (particularly, SMV datasets which also use filtered lists and checkboxes).

**Comment by danyill** [comment]
I am coming around (slowly) to the idea that this never worked.

`display:flex` in the CSS filter is overriding `display:false` used for the filtering and there are no tests of this functionality.

A hacky fix which allows filtering is:

```css
    mwc-check-list-item.hidden {
      display: none !important;
    }
```

**Comment by danyill** [comment]
I thought  a higher specificity selector making sure they were hidden would help, and it does:

```css
    /* items removed if they are in fact hidden due to a search (with higher specificity than the above display:flex rule) */
    .tGSEControlFilter[on] ~ .cleanupList > .tGSEControl.hidden,
    .tSampledValueControlFilter[on]
      ~ .cleanupList
      > .tSampledValueControl.hidden,
    .tLogControlFilter[on] ~ .cleanupList > .tLogControl.hidden,
    .tReportControlFilter[on] ~ .cleanupList > .tReportControl.hidden {
      display: none;
    }
```

But it is still broken; there is an order of operations which results in losing items if you play with the filters and the search input.

For example:

1. Start with `test/testfiles/cleanup.scd`
2. Turn on the `R` filter
3. Enter `cb` in the search window
4. Turn off `G` filter
5. Remove the words `cb` (backspace them)
6. Turn on `G` filter
7. Note that the GSEControl elements do not return

I think the underlying issue is that toggle icons and the search bar can't both mutate the `hidden` class correctly without awareness of why the "other filter" has changed the class on items.

What I think we need is for this container to be able to call `onFilterInput` from `filtered-list.ts`:

https://github.com/openscd/open-scd/blob/7a12d77447fcf2f24a8b7f3e2549ce1626f41774/src/filtered-list.ts#L84-L94

Calling `onFilterInput` would allow the text filter to be reapplied correctly after the filter buttons.
I'll propose a method to do this.

I've also made adding the `hidden` class more explicitly dependent on the filter state rather than simply toggling it. This seems better to avoid side effects.

I guess a test could be written which looked at the `hidden` attribute on the list elements, but otherwise, I guess a visual test would be better.
